# Get the growth rates of the immunocompetent mice

This file calculates the exponential growth rate of the immunocompetent B6 mice and generates Supplementary Table 2.

## Prep

Load required packages

In [10]:
%matplotlib widget
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import os
from estimator import Estimator
from src import pyxfunc

## Define data and user-input parameters

Define the data file, config file, save files, and group names

In [2]:
data_file = "data/growth_data_df.csv"
admix_result_path = "results/growth/"
config = "config_files/config_km.json"
b6_groups = ["Grp. A1 B6 (100% C1)", "Grp. A2 B6 (80% C1; 20% C11)", "Grp. A3 B6 (50% C1; 50% C11)", "Grp. A4 B6 (20% C1; 80% C11)", "Grp. A5 B6 (100% C11)"]
exclude = [456, 458, 461, 464, 471, 474, 478, 482, 483, 426, 428, 429, 430, 434, 437, 438, 442, 443, 451, 642, 662]

Create an estimator object from the config file

In [11]:
es = Estimator(config)

Load the growth data

In [12]:
growth_df = pd.read_csv(data_file)
growth_df = growth_df[~(growth_df["id"].isin(exclude))]
growth_df.loc[growth_df["group"]=="1C", "group"] = "Grp. A1 B6 (100% C1)"
growth_df.loc[growth_df["group"]=="2C", "group"] = "Grp. A2 B6 (80% C1; 20% C11)"
growth_df.loc[growth_df["group"]=="3C", "group"] = "Grp. A3 B6 (50% C1; 50% C11)"
growth_df.loc[growth_df["group"]=="4C", "group"] = "Grp. A4 B6 (20% C1; 80% C11)"
growth_df.loc[growth_df["group"]=="5C", "group"] = "Grp. A5 B6 (100% C11)"
growth_df = growth_df[growth_df["group"].isin(b6_groups)]
es.growth_df = growth_df
growth_df

                      group   id  day         size
0      Grp. A1 B6 (100% C1)  424    7    25.725600
1      Grp. A1 B6 (100% C1)  424   10    36.392700
2      Grp. A1 B6 (100% C1)  424   14    46.803512
3      Grp. A1 B6 (100% C1)  424   17    98.260390
4      Grp. A1 B6 (100% C1)  424   21   112.673203
...                     ...  ...  ...          ...
1125  Grp. A5 B6 (100% C11)  721   28   179.820056
1126  Grp. A5 B6 (100% C11)  721   32   270.999669
1127  Grp. A5 B6 (100% C11)  721   35   376.139244
1128  Grp. A5 B6 (100% C11)  721   39   804.311946
1129  Grp. A5 B6 (100% C11)  721   42  1194.541020

[727 rows x 4 columns]

Make a list of the growth rates to test

In [4]:
g_list = [round(0.01+0.001*i, 3) for i in range(round((.15-0.01)/0.001+1))]

## Estimate growth rates

Function to estimate the growth rate for each mouse

In [8]:
def get_grs():
    results = [[0]]*(len(growth_df["id"].unique())*len(g_list))
    idx = 0
    for mid in growth_df["id"].unique():
        for g_idx in range(len(g_list)):
            init = [growth_df[(growth_df["id"]==mid) & (growth_df["day"]==7)]["size"].iloc[0], 0, 0]
            end_time = max(growth_df[growth_df["id"] == mid]["day"])
            sol = pyxfunc.run(init[0], init[1], init[2], 7, end_time, np.inf, 
                                es.cutoff_0_raw, es.cutoff_0_percent, init[2],
                                g_list[g_idx], 0, 0, 0, 0, 0, 0, 0, 0)
            day_idxs = [(d-7)*100 for d in growth_df[growth_df["id"]==mid]["day"]]
            sizes = growth_df[growth_df["id"] == mid]["size"].tolist()
            err_win = pyxfunc.get_error(day_idxs, sizes, sol, 0, es.max_loser_subline_percent)
            results[idx] = [growth_df[(growth_df["id"]==mid)]["group"].tolist()[0], mid, g_list[g_idx], err_win[0], err_win[1]]
            idx += 1
    results = pd.DataFrame(results, columns=["group", "id", "g", "error", "winner"])
    results_best = results.groupby("id")[["group", "g", "error"]].apply(lambda x: x[x["error"]==x["error"].min()]).reset_index()
    results_best = results_best.drop("level_1", axis=1)
    return results_best

Get the growth rates

In [13]:
results_b6 = get_grs()
results_b6

     id                         group      g         error
0   424          Grp. A1 B6 (100% C1)  0.062   1424.881130
1   425          Grp. A1 B6 (100% C1)  0.048   1094.336786
2   427          Grp. A1 B6 (100% C1)  0.052    950.764380
3   431  Grp. A2 B6 (80% C1; 20% C11)  0.051   5741.269361
4   432  Grp. A2 B6 (80% C1; 20% C11)  0.035  14978.745755
5   433  Grp. A2 B6 (80% C1; 20% C11)  0.039   1802.389459
6   435  Grp. A2 B6 (80% C1; 20% C11)  0.060    771.601520
7   436  Grp. A3 B6 (50% C1; 50% C11)  0.051  19229.911190
8   439  Grp. A3 B6 (50% C1; 50% C11)  0.032   4017.765119
9   440  Grp. A3 B6 (50% C1; 50% C11)  0.043   5557.613127
10  441  Grp. A3 B6 (50% C1; 50% C11)  0.030  29884.070244
11  444  Grp. A4 B6 (20% C1; 80% C11)  0.061  42763.784306
12  445  Grp. A4 B6 (20% C1; 80% C11)  0.055  13451.281858
13  446  Grp. A4 B6 (20% C1; 80% C11)  0.055   3136.315934
14  447  Grp. A4 B6 (20% C1; 80% C11)  0.061   8195.899160
15  448         Grp. A5 B6 (100% C11)  0.112   3532.298039
16  449         Grp. A5 B6 (100% C11)  0.114   2574.264831
17  450         Grp. A5 B6 (100% C11)  0.126    426.032054
18  452         Grp. A5 B6 (100% C11)  0.081   5850.652906
19  453         Grp. A5 B6 (100% C11)  0.101   2604.141214
20  600          Grp. A1 B6 (100% C1)  0.079    972.340273
21  601          Grp. A1 B6 (100% C1)  0.078   1804.320215
22  602          Grp. A1 B6 (100% C1)  0.063   2515.497162
23  609          Grp. A1 B6 (100% C1)  0.087   4300.392722
24  627  Grp. A2 B6 (80% C1; 20% C11)  0.052  33513.459336
25  633  Grp. A2 B6 (80% C1; 20% C11)  0.037  17776.043551
26  637  Grp. A2 B6 (80% C1; 20% C11)  0.055  13978.823613
27  648  Grp. A2 B6 (80% C1; 20% C11)  0.072   5510.664212
28  653  Grp. A3 B6 (50% C1; 50% C11)  0.061   3550.740117
29  655  Grp. A3 B6 (50% C1; 50% C11)  0.073   6923.039476
30  660  Grp. A3 B6 (50% C1; 50% C11)  0.063   8016.601361
31  668  Grp. A3 B6 (50% C1; 50% C11)  0.068   7528.407852
32  683  Grp. A4 B6 (20% C1; 80% C11)  0.095   1448.869647
33  686  Grp. A4 B6 (20% C1; 80% C11)  0.102    898.408407
34  687  Grp. A4 B6 (20% C1; 80% C11)  0.069    696.643948
35  689  Grp. A4 B6 (20% C1; 80% C11)  0.065   4481.354970
36  697  Grp. A4 B6 (20% C1; 80% C11)  0.076   1632.302871
37  701         Grp. A5 B6 (100% C11)  0.103   2877.860505
38  703         Grp. A5 B6 (100% C11)  0.098    907.142665
39  704         Grp. A5 B6 (100% C11)  0.106   3194.327635
40  715         Grp. A5 B6 (100% C11)  0.094    898.240269
41  721         Grp. A5 B6 (100% C11)  0.117   2346.488722

In [ ]:
if admix_result_path:
    results_b6.to_csv(admix_result_path + "b6_growth_rates.csv")